### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by Mazinms** [skasperski/navigation_2d#18]
i keep running into this error, any idea what is going here
"CMake Error at /home/mazin/catkin_w/devel/share/costmap_2d/cmake/costmap_2dConfig.cmake:106 (message):
  Project 'costmap_2d' specifies
  '/home/mazin/catkin_w/src/navigation/costmap_2d/include' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '/home/mazin/catkin_w/src/navigation/costmap_2d//home/mazin/catkin_w/src/navigation/costmap_2d/include'.
  Ask the maintainer 'David V.  Lu!! davidvlu@gmail.com, Michael Ferguson
  mferguson@fetchrobotics.com' to fix it.
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  navigation_2d/nav2d_operator/CMakeLists.txt:5 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CSPARSE_INCLUDE_DIR
   used as include directory in directory /home/mazin/catkin_w/src/navigation_2d/nav2d_karto
   used as include directory in directory /home/mazin/catkin_w/src/navigation_2d/nav2d_karto
   used as include directory in directory /home/mazin/catkin_w/src/navigation_2d/nav2d_karto
CSPARSE_LIBRARY
    linked by target "mapper" in directory /home/mazin/catkin_w/src/navigation_2d/nav2d_karto

-- Configuring incomplete, errors occurred!
See also "/home/mazin/catkin_w/build/CMakeFiles/CMakeOutput.log".
See also "/home/mazin/catkin_w/build/CMakeFiles/CMakeError.log".
make: **\* [cmake_check_build_system] Error 1
"

**Comment by skasperski** [comment]
About the CSPARSE_LIBRARY: Have you installed libsuitesparse-dev on your system? This is only done automatically when you install from debian packages.

About costmap_2d: Is costmap_2d also installed from source? Please make sure that both costmap_2d and nav2d are on an indigo branch.
