### ISSUE TITLE
Troubles with autonomouse mapping with nav2d and turtlebot 2 - StartExploration Error 

### ISSUE THREAD

**Issue by paddi00** [skasperski/navigation_2d#21]
Hi, 

I already made a thread on answers.ros.org. Unfortunately, you haven´t been online since I opened this thread. The link is:
http://answers.ros.org/question/239616/troubles-with-autonomouse-mapping-with-nav2d-and-turtlebot-2-startexploration-error/

I don´t want to annoy you with my problem but I could need a little bit of help.

Thanks

**Comment by skasperski** [comment]
Replied on ROS-Answers.
