### ISSUE TITLE
What kind of vehicles is the path planning written for?

### ISSUE THREAD

**Issue by glebos** [skasperski/navigation_2d#22]
Hi,
I'm wondering if the navigation and path planning is applicable for a front steering chassis with higher turn radius? Is this navigation package written for a special kind of robot or is it universal?
Kind regards.

**Comment by skasperski** [comment]
The path planning in nav2d_navigator is currently suited for holonomic robots with a nearly circular footprint only. It uses a simple grid-based shortest path algorithm and follows this path as good as possible. For a front steering chassis you need a more sophisticated path planner like [sbpl](http://wiki.ros.org/sbpl).

**Comment by glebos** [comment]
Ok, thank you for the answer.
