### ISSUE TITLE
For centralized operations, reducing to single mapper rather than one for each robot

### ISSUE THREAD

**Issue by nitin5** [skasperski/navigation_2d#34]
Greetings,
I was executing experimentation with the code. I realize that exploration and mapper is running on each robot. Since all robots are connected, it may as well be beneficial computationally if a single mapper runs and map is shared with others. There may be different navigator packages for each robot. As one robot localize in the map of another robot, we can get a single tf tree. 
 I will like to know the design thoughts behind the current deployment approach. I understand one is that if either way they go out of communication range, each robot can function in  stand alone capacity.

Regards
Nitin

**Comment by skasperski** [comment]
Hello,
sorry, I somehow missed this. The idea is exactly as you already figured out: Having all robots using one mapper instance and sharing a tf-tree if very susceptible to communication loss. It was particular important to not have a centralized approach, but a distributed one, where each robot can continuously  operate and map without constant connection to the other robots.
