### ISSUE TITLE
Layered-costmap with second laserScan

### ISSUE THREAD

**Issue by Han-IChun** [skasperski/navigation_2d#37]
Hi skasperski,
I'm trying to create a layered-cosmap by costmap2d plugin module with seceond laserScan.
Should the Operaor node subscribe to the second laserSacn? or just add another observation source  on costmap.yaml and specify a frame and a topic?

Many thanks,
I-chun

**Comment by skasperski** [comment]
Hi I-Chun,
I think this should be done as you suggested via the costmap.yaml. The Costmap handles all the incoming sensor readings by itself, so there is no need to do this in the Operator. (The Operator also does not subscribe to the laser-scan itself, because it is managed by the costmap.)
