### ISSUE TITLE
Compilation with gcc7

### ISSUE THREAD

**Issue by MaxGsomGsom** [skasperski/navigation_2d#44]
The same bug as here https://github.com/ros-planning/navigation/pull/587/commits/65261a83e7269906f726f14d7e8cc30e5f9901f0

https://github.com/skasperski/navigation_2d/blob/711a5609dcb9f47fc2ccec445762c9043bdf0d0e/nav2d_localizer/src/map/map_cspace.cpp#L89-L100

**Comment by skasperski** [comment]
Copied the fix from navigation package to master. 
beeae18c18b24dd604aba1f000e43364f3bafc86
Please verify that it solves this issue and close it.

**Comment by MaxGsomGsom** [comment]
Now it's ok
