### ISSUE TITLE
LIDAR to Costmap

### ISSUE THREAD

**Issue by CapitalZe** [skasperski/navigation_2d#47]
Which nodes must I modify to have my actual LIDAR provide data for the costmap and to generate the map?

I've been looking a while and trying multiple things, but can not seem to pinpoint where it is. I've been tending towards the MultiMapper.cpp node but had no success yet.

In RViz I can see my LIDAR superimposed above the generated map and costmap, but it is just visible data at this point. It doesn't have any influence.

Many thanks!

**Comment by skasperski** [comment]
Both the mapper and the costmap subscribe to the /scan topic. You can remap topic names in the launch file with the `<remap>` tag, there is no need to change any source code.

See here for an example:
https://github.com/skasperski/navigation_2d/blob/master/nav2d_tutorials/launch/tutorial1.launch#L14

Please note that this kind of questions is better suited for [ROS-Answers](https://answers.ros.org).
