### ISSUE TITLE
Build-Error on Kinetic

### ISSUE THREAD

**Issue by kadupitiya** [skasperski/navigation_2d#50]
Hi,
I am new to ROS and I am trying to build nav_2d with kinetic.
I get following error:
/home/kadupitiya/catkin_ws/src/navigation_2d/nav2d_operator/src/RobotOperator.cpp:11:66: error: no matching function for call to ‘costmap_2d::Costmap2DROS::Costmap2DROS(const char [10], tf2_ros::Buffer&)’
  mLocalMap = new costmap_2d::Costmap2DROS("local_map", mTf2Buffer);
Please let me know what is the issue.

**Comment by skasperski** [comment]
Have you checked out the branch "kinetic" of this package?

**Comment by kadupitiya** [comment]
I am sorry I had an issue in my ubuntu version.
